import './catalogFilters'
import './catalogFilter'
import './catalogAside'

import './catalog.scss'
import './catalogFilters.scss'
import './catalogFilter.scss'
import './catalogAside.scss'
import './catalogNav.scss'
import './catalogSort.scss'

import 'src/assets/img/catalog/shape-asher.svg'
import 'src/assets/img/catalog/shape-baget.svg'
import 'src/assets/img/catalog/shape-brilliant.svg'
import 'src/assets/img/catalog/shape-corazon.svg'
import 'src/assets/img/catalog/shape-izumrud.svg'
import 'src/assets/img/catalog/shape-kushon.svg'
import 'src/assets/img/catalog/shape-markiz.svg'
import 'src/assets/img/catalog/shape-octagon.svg'
import 'src/assets/img/catalog/shape-ovalado.svg'
import 'src/assets/img/catalog/shape-pera.svg'
import 'src/assets/img/catalog/shape-princesa.svg'
import 'src/assets/img/catalog/shape-radiant.svg'
import 'src/assets/img/catalog/shape-triangulo.svg'
import 'src/assets/img/catalog/multicolor.png'
import 'src/assets/img/catalog/transparent.png'
