import './footer'
import './footer.scss'
import 'src/assets/img/footer/telegram.svg'
import 'src/assets/img/footer/vk.svg'
import 'src/assets/img/footer/appstore.svg'
import 'src/assets/img/footer/googleplay.svg'
