import './sectionHero'
import './sectionHero.scss'
// import 'src/assets/img/sectionHero/slide-img-mobile.jpg'
// import 'src/assets/img/sectionHero/slide-img-desktop.jpg'
import 'src/assets/video/sectionHero/slide-1-mobile.mp4'
import 'src/assets/video/sectionHero/slide-1-desktop.mp4'
import 'src/assets/img/sectionHero/slide-2-mobile-content.jpg'
import 'src/assets/img/sectionHero/slide-2-desktop-content.jpg'
import 'src/assets/img/sectionHero/slide-3-mobile-content.jpg'
import 'src/assets/img/sectionHero/slide-3-desktop-content.jpg'
import 'src/assets/img/sectionHero/slide-4-mobile-content.jpg'
import 'src/assets/img/sectionHero/slide-4-desktop-content.jpg'
