import 'restyle.css/dist/restyle.css'
import 'restyle.css/dist/scrollbar.css'
import 'restyle.css/dist/checkboxes.css'
import 'swiper/swiper-bundle.css'
import 'src/styles/main.scss'
import 'src/views/components'
